name: agro_vision
description: "A graduation project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.13
  animated_bottom_navigation_bar: ^1.3.3
  font_awesome_flutter: ^10.8.0
  pin_code_fields: ^8.0.1
  otp_timer_button: ^1.1.1
  flutter_otp_text_field: ^1.2.0
  flutter_launcher_icons: ^0.14.1
  fl_chart: ^0.69.2
  http: ^1.2.2
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5
  lottie: ^3.1.3
  image_picker: ^1.1.2
  sliding_clipped_nav_bar: ^3.1.0+4
  syncfusion_flutter_gauges: ^28.1.33
  shimmer: ^2.0.0
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  cached_network_image: ^3.4.1
  meta: ^1.9.1
  iconsax: ^0.0.8
  flutter_sound: ^9.28.0
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^11.4.0
  audioplayers: ^6.4.0
  audio_waveforms: ^1.3.0
  provider: ^6.1.4
  socket_io_client: ^3.1.1
  flutter_markdown: ^0.7.7
  animate_do: ^4.2.0
  flutter_local_notifications: ^19.1.0
  share_plus: ^11.0.0
  ffmpeg_kit_flutter_new: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/images/onboarding/
    - assets/images/authentication/
    - assets/icon/
    - assets/animations/
    - assets/animations/weather/
    - assets/icon/weather_icons/
    - assets/images/sensor_icon/
    - shorebird.yaml
    - .env
  fonts:
    - family: DIN
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Medium.ttf
        - asset: assets/fonts/DINNextLTArabic-Regular.ttf


    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-VariableFont_wght.ttf

    - family: PTS
      fonts:
        - asset: assets/fonts/PTSans-Bold.ttf
        - asset: assets/fonts/PTSans-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
