class AppRoutes {
  AppRoutes._();
  static const String onBoardingScreen = "/onBoardingScreen";
  static const String loginScreen = "/loginScreen";
  static const String logout = "/logout";
  static const String splashScreen = "/splashScreen";
  static const String screenLayout = "/screenLayout";
  static const String homeScreen = "/homeScreen";
  static const String forgotPasswordPhone = "/forgotPasswordPhone";
  static const String otpPhoneScreen = "/otpPhoneScreen";
  static const String forgotPasswordEmail = "/forgotPasswordEmail";
  static const String otpEmailScreen = "/otpEmailScreen";
  static const String createNewPassword = "/CreateNewPassword";
  static const String congratulationsScreen = "/congratulationsScreen";
  static const String notificationsScreen = "/notificationsScreen";
  static const String seeAllNotes = "/seeAllNotes";
  static const String seeAllFields = "/seeAllFields";
  static const String sensorDataScreen = "/sensorDataScreen";
  static const String addNewNote = "/addNewNote";
  static const String editNoteScreen = "/editNoteScreen";
  static const String chatList = '/chat-list';
  static const String chatDetail = '/chat-detail';
  static const String communityChat = '/community-chat';
  static const String consultationChat = '/consultation-chat';
  static const String farmAnalytics = '/farmAnalytics-chat';
  static const String cropsManagment = '/cropsManagment-chat';
  static const String farmInventory = '/farmInventory-chat';
  static const String team = '/team';
  static const String settingsScreen = '/settingsScreen';
  static const String profileScreen = '/profileScreen';
  static const String editProfileScreen = '/editProfileScreen';
}
